version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  mysql:
    image: "mysql"
    command: "--default-authentication-plugin=mysyql_native_password"
    restart: "always"
    environment: 
      MYSQL_ROOT_PASSWORD: "goku"
